name: AdvancementTags
version: '1.4'
main: net.gg.tech.advancementTags.AdvancementTags
api-version: '1.21.1'
load: STARTUP
authors: [ _ItzTech ]
description: Private TechSMP plugin for the Advancement System
